#!/usr/bin/ruby
# Creates a qmake .pro file for all valid SOURCES, HEADERS, FORMS and
# RESOURCES under each argument to ARGV as directories

cwd=File.dirname __FILE__
require 'find'
require "#{cwd}/findsrc"

sources = Array.new
headers = Array.new
forms = Array.new
resources = Array.new

$findsrc_prune_pro=true

ARGV.each do |d|
  Dir.chdir d do
    findsrc do |path,ext|
      case ext
        when ".h"   then headers   << path
        when ".ui"  then forms     << path
        when ".qrc" then resources << path
        when ".cpp" then sources   << path
      end
    end
  end
end

def puts_section section, files
  return if files.empty?
  print section + " ="
  files.each do |filename|
    print " \\\n\t"
    print filename
  end
  puts
end

puts_section "SOURCES", sources
puts_section "HEADERS", headers
puts_section "FORMS", forms
puts_section "RESOURCES", resources
